services:
  - type: web
    name: misinfo-detector
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential gcc
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
